spring.application.name=GreenGuard-Web
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_green_guardian
spring.datasource.username=postgres
spring.datasource.password=postgre

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Crea variables de entorno en tu pc para q te lea estos valores

cloudinary.name = {CLOUDINARY_NAME}
cloudinary.key = {CLOUDINARY_KEY}
cloudinary.secret = {CLOUDINARY_SECRET}

# Para el chatbot
openai.api.key = {OPEN_AI_KEY}
openai.api.url = https://api.openai.com/v1/chat/completions
openai.api.model = gpt-4o-mini