spring.application.name=GreenGuard-Web
spring.datasource.url=jdbc:postgresql://localhost:5432/DB_GREENGUARD
spring.datasource.username=postgres
spring.datasource.password=sql

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Cambiar la ip con el de tu dispositivo fisico, menos el 8000
python.ai.service.url=http://192.168.1.10:8000
server.port=8080
#Crea variables de entorno en tu pc para q te lea estos valores

cloudinary.name = {CLOUDINARY_NAME}
cloudinary.key = {CLOUDINARY_KEY}
cloudinary.secret = {CLOUDINARY_SECRET}

#variables para la IA
openai.api.key = {OPEN_AI_KEY}
openai.api.url = https://api.openai.com/v1/chat/completions
openai.api.model = gpt-4o-mini
