
INSERT INTO tb_tipo_notificacion(descripcion) VALUES

('REPORTE_PENDIENTE'),
('REPORTE_EN_PROCESO'),
('REPORTE_RESUELTO'),
('REPORTE_CANCELADO'),
('PUNTOS_GANADOS'),
('BONUS_MULTIPLO_5'),
('CUPON_DISPONIBLE'),
('CUPON_POR_VENCER'),
('CUPON_VENCIDO');
